development:
  adapter: postgresql
  encoding: unicode
  database: contact
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: contact
  pool: 2

production:
  adapter: postgresql
  encoding: unicode
  database: contact
  pool: 2
